### ISSUE TITLE
Locking Actors counts as a changed file

### ISSUE THREAD

**Issue by soraphis** [Gradess2019/ActorLocker#1]
when toggling visibility (the eye icon) it does not modify the level, but when locking it does.

also when using the "one actor one file" mode with world partition, those all count as changed files and working with other people means locking can lead to conflicts and lock state is shared across the team

I guess that this is a limitation in the implementation as it's using an tag on the actor...

**Comment by soraphis** [comment]
I found out, that you can disable the tagging in the editor preferences. 
leaving this here, in case someone stumbles over it.

**Comment by Gradess2019** [comment]
Yes, currently its using tags for locking. One day I will implement better approach, but this way was the most easies and convenient during development.
