### ISSUE TITLE
[AC-29] GPL License...

### ISSUE THREAD

**Issue by soraphis** [Gradess2019/ActorLocker#2]
... If I understand it correctly the usage of an GPL License makes this plugin unusable for everything more than a prototype.

Working on a commercial game with the goal to distribute the games binaries, would mean that the whole source code of the project also needs to be disclosed. right?

The only thing one could argue about it, would be that it's an editor plugin and that part of the project is not shipped with the games binaries... but still, feels weird to me.

**Comment by soraphis** [comment]
Also based on the Unreal Engine EULA: https://www.unrealengine.com/en-US/eula/unreal

GPL is a "non compatible license" and it's not permitted to **combine** or distribute the engine, or parts of it, with GPL covered software

**Comment by Gradess2019** [comment]
Fixed in [1.5.3](https://github.com/Gradess2019/ActorLocker/releases/tag/1.5.3)
