### ISSUE TITLE
[AC-28] Epic Store release only supports Windows

### ISSUE THREAD

**Issue by wallywyyoung** [Gradess2019/ActorLocker#5]
Hello- Is there anything in the plugin which would make it only single-platform? For some reason I cannot install this plugin to UE on my Mac. Thank you.

**Comment by Gradess2019** [comment]
Heyo!
I haven't marked the product for Mac and Linux, since I don't have neither, and if there would be any specific crashes / bugs, it could block the submission and release process.

**Comment by Gradess2019** [comment]
Added Linux and MacOS platforms as supported to UE marketplace
